version: "3.8"

services:
  db_archives:
    image: postgres:11-alpine

    env_file:
      - ./.env

    volumes:
      - postgres_data_archives:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web_archives:
    build: .

    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8002"

    env_file:
      - ./.env

    volumes:
      - .:/code

      # o volume garante que as alterações realizadas no projeto sejam propagadas no container

    ports:
      - "8002:8002"

    depends_on:
      db_archives:
        condition: service_healthy

volumes:
  postgres_data_archives:
